### ISSUE TITLE
Proposed feature: only store first n outputs from simulation function

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xgrid#40]
## Proposed feature
All the setting of a parameter, `n_outputs` in the `xgrid` object that determines how many outputs of the simulation function to save.

This allows simulation functions to save the full state or time series of the system as nth outputs, but not have to save them for each trial. 

This functionality was intended (the parameter already exists).

## Changes
Line 61 in `simulate_core` needs to be adjusted to use this parameter.

**Comment by alec-hoyland** [comment]
I'll work on this when I've got the time.

**Comment by sg-s** [comment]
This is a great idea

**Comment by alec-hoyland** [comment]
PR #41 fixes this issue. `n_outputs` wasn't used anywhere, despite being defined, so I used it for what I presume was its intended purpose.
